@extends('errors.layout')

@section('status', '403')
@section('title', 'Acceso restringido')
@section('eyebrow', 'Permisos insuficientes')
@section('message', 'Tu usuario no tiene permisos para consultar esta zona de la plataforma.')
@section('detail', 'Si deberias tener acceso, solicita a un administrador que revise tus permisos de organizacion o sitio.')
@section('primaryLabel', 'Ir al dashboard')
@section('primaryHref', route('dashboard'))
@section('secondaryLabel', 'Volver al inicio')
@section('secondaryHref', url('/'))
@section('panelTitle', 'Acceso bloqueado')
@section('panelText', 'La plataforma ha protegido este recurso porque tu sesion no cumple los permisos requeridos.')
@section('tone', 'warning')
