@extends('errors.layout')

@section('status', '404')
@section('title', 'Pagina no encontrada')
@section('eyebrow', 'Ruta no disponible')
@section('message', 'La ruta solicitada no existe o se ha movido dentro de energiaMonitor.')
@section('detail', 'Comprueba la direccion o vuelve al inicio para acceder de nuevo a tus paneles, informes y configuracion.')
@section('primaryLabel', 'Volver al inicio')
@section('primaryHref', url('/'))
@section('secondaryLabel', 'Ir al dashboard')
@section('secondaryHref', route('dashboard'))
@section('panelTitle', 'Ruta sin destino')
@section('panelText', 'La solicitud no coincide con ninguna pantalla activa de la plataforma.')
@section('tone', 'neutral')
