@extends('errors.layout')

@section('status', '419')
@section('title', 'Sesion expirada')
@section('eyebrow', 'Sesion protegida')
@section('message', 'La sesion ha caducado por seguridad o por inactividad.')
@section('detail', 'Inicia sesion de nuevo para continuar trabajando con tus datos energeticos sin perder el contexto operativo.')
@section('primaryLabel', 'Iniciar sesion')
@section('primaryHref', route('login'))
@section('secondaryLabel', 'Volver al inicio')
@section('secondaryHref', url('/'))
@section('panelTitle', 'Sesion cerrada')
@section('panelText', 'El token de seguridad ya no es valido y necesitamos confirmar tu identidad otra vez.')
@section('tone', 'session')
