@extends('errors.layout')

@section('status', '500')
@section('title', 'Incidencia tecnica')
@section('eyebrow', 'Error interno')
@section('message', 'No hemos podido completar la solicitud en este momento.')
@section('detail', 'Nuestro sistema ha registrado la incidencia. Puedes volver al inicio y reintentar la operacion en unos minutos.')
@section('primaryLabel', 'Volver al inicio')
@section('primaryHref', url('/'))
@section('secondaryLabel', 'Iniciar sesion')
@section('secondaryHref', route('login'))
@section('panelTitle', 'Solicitud interrumpida')
@section('panelText', 'Un proceso interno ha detenido la respuesta antes de completar la operacion.')
@section('tone', 'warning')
