@extends('errors.layout')

@section('status', '503')
@section('title', 'Mantenimiento programado')
@section('eyebrow', 'Plataforma en mantenimiento')
@section('message', 'Estamos actualizando la plataforma para mejorar la monitorizacion energetica.')
@section('detail', 'Las lecturas, alertas e informes volveran a estar disponibles cuando termine la intervencion. No necesitas hacer ningun cambio en tu cuenta.')
@section('primaryLabel', 'Volver a comprobar')
@section('primaryHref', url()->current())
@section('secondaryLabel', 'Ir al inicio')
@section('secondaryHref', url('/'))
@section('panelTitle', 'Intervencion activa')
@section('panelText', 'El acceso se ha pausado temporalmente mientras aplicamos cambios de mantenimiento.')
@section('tone', 'maintenance')
